/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import config.config;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.sql.*;
    

public class AdminDashboard extends javax.swing.JFrame {

    private String loggedInUsername;
    private int adminId;
    
    // Tables
    private DefaultTableModel modelUsers;
    private DefaultTableModel modelProjects;
    private DefaultTableModel modelPayments;
    private DefaultTableModel modelContractors;
    private DefaultTableModel modelClients;
    private DefaultTableModel modelPending;
    
    private JTable tblUsers;
    private JTable tblProjects;
    private JTable tblPayments;
    private JTable tblContractors;
    private JTable tblClients;
    private JTable tblPending;
    
    // Sorters for search
    private TableRowSorter<DefaultTableModel> sorterUsers;
    private TableRowSorter<DefaultTableModel> sorterProjects;
    private TableRowSorter<DefaultTableModel> sorterPayments;
    private TableRowSorter<DefaultTableModel> sorterContractors;
    private TableRowSorter<DefaultTableModel> sorterClients;
    private TableRowSorter<DefaultTableModel> sorterPending;
    
    // Dashboard stats
    private JLabel lblTotalUsers;
    private JLabel lblTotalProjects;
    private JLabel lblTotalContractors;
    private JLabel lblTotalRevenue;
    

    public AdminDashboard(String username) {
        this.loggedInUsername = username;
        initComponents();
        getAdminId();
        jLabel2.setText("WELCOME, " + username.toUpperCase());
        setupAllTabs();
        loadDashboardStats();
        loadAllData();
    }

       
        /*  displayData("SELECT * FROM users", jTableUsers);*/

  
    private void getAdminId() {
       try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            String sql = "SELECT id FROM users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, loggedInUsername);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) adminId = rs.getInt("id");
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   private void setupAllTabs() {
        setupProfileTab();
        setupDashboardTab();
        setupUsersTab();
        setupProjectsTab();
        setupPaymentsTab();
        setupContractorsTab();
        setupClientsTab();
        setupPendingTab();
    }

    private void loadDashboardStats() {
        try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            ResultSet r1 = conn.createStatement().executeQuery("SELECT COUNT(*) as c FROM users");
            if (r1.next()) lblTotalUsers.setText(String.valueOf(r1.getInt("c")));
            r1.close();
            
            try {
                ResultSet r2 = conn.createStatement().executeQuery("SELECT COUNT(*) as c FROM projects");
                if (r2.next()) lblTotalProjects.setText(String.valueOf(r2.getInt("c")));
                r2.close();
            } catch (Exception e) { lblTotalProjects.setText("0"); }
            
            ResultSet r3 = conn.createStatement().executeQuery("SELECT COUNT(*) as c FROM users WHERE role = 'contractor' AND status = 'approved'");
            if (r3.next()) lblTotalContractors.setText(String.valueOf(r3.getInt("c")));
            r3.close();
            
            try {
                ResultSet r4 = conn.createStatement().executeQuery("SELECT SUM(amount) as t FROM payments");
                if (r4.next()) lblTotalRevenue.setText("₱" + String.format("%.2f", r4.getDouble("t")));
                r4.close();
            } catch (Exception e) { lblTotalRevenue.setText("₱0.00"); }
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadAllData() {
        loadUsers();
        loadProjects();
        loadPayments();
        loadContractors();
        loadClients();
        loadPending();
    }


   

   
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME, ADMIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 120));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("  👤 My Profile");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("📊 Dashboard");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("👥 Manage Users ");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("📁 Manage Projects");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("💰 View Payments ");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        jButton7.setBackground(new java.awt.Color(0, 0, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("🔧 View Contractors ");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 30));

        jButton8.setBackground(new java.awt.Color(0, 0, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText(" 🏢 View Clients ");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 30));

        jButton9.setBackground(new java.awt.Color(0, 0, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("⏳ Pending Users");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 430));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", jPanel10);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 480, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int confirm = JOptionPane.showConfirmDialog(this, "Logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login.Login().setVisible(true);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jTabbedPane1.setSelectedIndex(1);
        loadDashboardStats();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      jTabbedPane1.setSelectedIndex(2);
        loadUsers();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jTabbedPane1.setSelectedIndex(3);
        loadProjects();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    jTabbedPane1.setSelectedIndex(4);
        loadPayments();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jTabbedPane1.setSelectedIndex(5);
        loadContractors();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      jTabbedPane1.setSelectedIndex(6);
        loadClients();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      jTabbedPane1.setSelectedIndex(7);
        loadPending();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new AdminDashboard("admin").setVisible(true));
    }
    
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
    
    
    private void loadUsers() {
       try {
            modelUsers.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT id, username, role, status FROM users WHERE status = 'approved' ORDER BY id";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelUsers.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("role") != null ? rs.getString("role").toUpperCase() : "—",
                    rs.getString("status").toUpperCase()
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadProjects() {
           try {
            modelProjects.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT p.id, p.project_name, " +
                        "c.username as client, " +
                        "COALESCE(co.username, 'None') as contractor, " +
                        "p.status " +
                        "FROM projects p " +
                        "JOIN users c ON p.client_id = c.id " +
                        "LEFT JOIN users co ON p.contractor_id = co.id " +
                        "ORDER BY p.id DESC";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelProjects.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    rs.getString("client"),
                    rs.getString("contractor"),
                    rs.getString("status")
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadPayments() {
        try {
            modelPayments.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT pay.id, p.project_name, pay.amount, pay.payment_date, pay.status " +
                        "FROM payments pay " +
                        "JOIN projects p ON pay.project_id = p.id " +
                        "ORDER BY pay.id DESC";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelPayments.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    "₱" + String.format("%.2f", rs.getDouble("amount")),
                    rs.getString("payment_date"),
                    rs.getString("status")
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadContractors() {
          try {
            modelContractors.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT id, username, status FROM users WHERE role = 'contractor' AND status = 'approved' ORDER BY id";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelContractors.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("status").toUpperCase()
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadClients() {
       try {
            modelClients.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT id, username, status FROM users WHERE role = 'client' AND status = 'approved' ORDER BY id";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelClients.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("status").toUpperCase()
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadPending() {
        try {
            modelPending.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT id, username, role, status FROM users " +
                        "WHERE role IS NOT NULL AND role != 'admin' " +
                        "AND (status = 'pending' OR status IS NULL OR status = '') " +
                        "ORDER BY id";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            
            while (rs.next()) {
                modelPending.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("role") != null ? rs.getString("role").toUpperCase() : "—",
                    "PENDING"
                });
            }
            
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setupProfileTab() {
        jPanel3.setLayout(null);
        jPanel3.setBackground(new Color(245, 247, 250));
        
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBounds(60, 30, 350, 320);
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        
        JPanel avatar = new JPanel();
        avatar.setBounds(125, 20, 100, 100);
        avatar.setBackground(new Color(168, 85, 247));
        avatar.setLayout(new BorderLayout());
        JLabel avatarLbl = new JLabel("👤", SwingConstants.CENTER);
        avatarLbl.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 50));
        avatarLbl.setForeground(Color.WHITE);
        avatar.add(avatarLbl);
        card.add(avatar);
        
        JLabel lblName = new JLabel(loggedInUsername.toUpperCase(), SwingConstants.CENTER);
        lblName.setBounds(25, 130, 300, 35);
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 24));
        card.add(lblName);
        
        JLabel lblRole = new JLabel("ADMIN", SwingConstants.CENTER);
        lblRole.setBounds(100, 170, 150, 30);
        lblRole.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblRole.setForeground(Color.WHITE);
        lblRole.setBackground(new Color(220, 38, 38));
        lblRole.setOpaque(true);
        card.add(lblRole);
        
        JLabel lblId = new JLabel("User ID: " + adminId);
        lblId.setBounds(25, 230, 300, 25);
        lblId.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        card.add(lblId);
        
        JLabel lblStatus = new JLabel("● Super Admin");
        lblStatus.setBounds(25, 260, 300, 25);
        lblStatus.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblStatus.setForeground(new Color(34, 197, 94));
        card.add(lblStatus);
        
        jPanel3.add(card);
    }

    private void setupDashboardTab() {
         jPanel4.setLayout(null);
        jPanel4.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("SYSTEM OVERVIEW");
        title.setFont(new Font("Segoe UI", Font.BOLD, 22));
        title.setBounds(20, 15, 400, 30);
        jPanel4.add(title);
        
        JPanel c1 = createCard("👥 Users", "0", 20, 60, new Color(59, 130, 246));
        JPanel c2 = createCard("📁 Projects", "0", 250, 60, new Color(34, 197, 94));
        JPanel c3 = createCard("🔧 Contractors", "0", 20, 210, new Color(251, 146, 60));
        JPanel c4 = createCard("💰 Revenue", "₱0.00", 250, 210, new Color(168, 85, 247));
        
        jPanel4.add(c1);
        jPanel4.add(c2);
        jPanel4.add(c3);
        jPanel4.add(c4);
    }
    private void setupUsersTab() {
        jPanel5.setLayout(null);
        jPanel5.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("👥 MANAGE USERS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel5.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel5.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel5.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel5.add(btnClear);
        
        String[] cols = {"ID", "Username", "Role", "Status"};
        modelUsers = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblUsers = createTable(modelUsers);
        sorterUsers = new TableRowSorter<>(modelUsers);
        tblUsers.setRowSorter(sorterUsers);
        
        JScrollPane sp = new JScrollPane(tblUsers);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel5.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadUsers());
        jPanel5.add(btnRefresh);
        
        setupSearch(txtSearch, sorterUsers, btnClear);
    }

   private JTable createTable(DefaultTableModel model) {
       JTable tbl = new JTable(model);
        tbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tbl.setRowHeight(28);
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl.setSelectionBackground(new Color(219, 234, 254));
        tbl.setGridColor(new Color(226, 232, 240));
        return tbl;
    }

     private JButton createBtn(String text, int x, int y, int w, int h, Color bg) {
        JButton btn = new JButton(text);
        btn.setBounds(x, y, w, h);
        btn.setBackground(bg);
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setFocusPainted(false);
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(bg.darker());
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(bg);
            }
        });
        return btn;
    }

   private void setupSearch(JTextField txtSearch, TableRowSorter<DefaultTableModel> sorter, JButton btnClear) {
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorter.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorter.setRowFilter(null);
        });
    }

   private JTextField createSearchField(int x, int y) {
        JTextField txt = new JTextField();
        txt.setBounds(x + 30, y, 315, 30);
        txt.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txt.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        return txt;
    }


    private JPanel createCard(String title, String value, int x, int y, Color color) {
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBounds(x, y, 210, 130);
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        
        JPanel bar = new JPanel();
        bar.setBounds(0, 0, 5, 130);
        bar.setBackground(color);
        card.add(bar);
        
        JLabel lbl1 = new JLabel(title);
        lbl1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lbl1.setForeground(new Color(100, 116, 139));
        lbl1.setBounds(15, 15, 190, 20);
        card.add(lbl1);
        
        JLabel lbl2 = new JLabel(value);
        lbl2.setFont(new Font("Segoe UI", Font.BOLD, 32));
        lbl2.setBounds(15, 60, 190, 40);
        card.add(lbl2);
        
        if (title.contains("Users")) lblTotalUsers = lbl2;
        else if (title.contains("Projects")) lblTotalProjects = lbl2;
        else if (title.contains("Contractors")) lblTotalContractors = lbl2;
        else if (title.contains("Revenue")) lblTotalRevenue = lbl2;
        
        return card;
    }

    private JButton createClearButton(int x, int y) {
       JButton btn = new JButton("✕");
        btn.setBounds(x, y, 50, 30);
        btn.setBackground(Color.WHITE);
        btn.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setFocusPainted(false);
        return btn;
    }

    private void setupProjectsTab() {
       jPanel6.setLayout(null);
        jPanel6.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("📁 MANAGE PROJECTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel6.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel6.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel6.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel6.add(btnClear);
        
        String[] cols = {"ID", "Project", "Client", "Contractor", "Status"};
        modelProjects = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblProjects = createTable(modelProjects);
        sorterProjects = new TableRowSorter<>(modelProjects);
        tblProjects.setRowSorter(sorterProjects);
        
        JScrollPane sp = new JScrollPane(tblProjects);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel6.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadProjects());
        jPanel6.add(btnRefresh);
        
        setupSearch(txtSearch, sorterProjects, btnClear);
    }

    private void setupPaymentsTab() {
         jPanel7.setLayout(null);
        jPanel7.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("💰 VIEW PAYMENTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel7.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel7.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel7.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel7.add(btnClear);
        
        String[] cols = {"ID", "Project", "Amount", "Date", "Status"};
        modelPayments = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPayments = createTable(modelPayments);
        sorterPayments = new TableRowSorter<>(modelPayments);
        tblPayments.setRowSorter(sorterPayments);
        
        JScrollPane sp = new JScrollPane(tblPayments);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel7.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadPayments());
        jPanel7.add(btnRefresh);
        
        setupSearch(txtSearch, sorterPayments, btnClear);
    }


    private void setupContractorsTab() {
         jPanel8.setLayout(null);
        jPanel8.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("🔧 VIEW CONTRACTORS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel8.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel8.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel8.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel8.add(btnClear);
        
        String[] cols = {"ID", "Username", "Status"};
        modelContractors = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblContractors = createTable(modelContractors);
        sorterContractors = new TableRowSorter<>(modelContractors);
        tblContractors.setRowSorter(sorterContractors);
        
        JScrollPane sp = new JScrollPane(tblContractors);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel8.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadContractors());
        jPanel8.add(btnRefresh);
        
        setupSearch(txtSearch, sorterContractors, btnClear);
    }

    private void setupClientsTab() {
      jPanel9.setLayout(null);
        jPanel9.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("🏢 VIEW CLIENTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel9.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel9.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel9.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel9.add(btnClear);
        
        String[] cols = {"ID", "Username", "Status"};
        modelClients = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblClients = createTable(modelClients);
        sorterClients = new TableRowSorter<>(modelClients);
        tblClients.setRowSorter(sorterClients);
        
        JScrollPane sp = new JScrollPane(tblClients);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel9.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadClients());
        jPanel9.add(btnRefresh);
        
        setupSearch(txtSearch, sorterClients, btnClear);
    }

    private void setupPendingTab() {
         jPanel10.setLayout(null);
        jPanel10.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("⏳ PENDING USERS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel10.add(title);
        
        // SEARCH BAR
        JTextField txtSearch = createSearchField(15, 50);
        jPanel10.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel10.add(searchIcon);
        
        JButton btnClear = createClearButton(360, 50);
        jPanel10.add(btnClear);
        
        String[] cols = {"ID", "Username", "Role", "Status"};
        modelPending = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPending = createTable(modelPending);
        sorterPending = new TableRowSorter<>(modelPending);
        tblPending.setRowSorter(sorterPending);
        
        JScrollPane sp = new JScrollPane(tblPending);
        sp.setBounds(15, 90, 445, 180);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel10.add(sp);
        
        JButton btnApprove = createBtn("✓ APPROVE", 15, 280, 110, 35, new Color(34, 197, 94));
        btnApprove.addActionListener(e -> approveUser());
        jPanel10.add(btnApprove);
        
        JButton btnDelete = createBtn("✗ DELETE", 135, 280, 100, 35, new Color(220, 38, 38));
        btnDelete.addActionListener(e -> deleteUser());
        jPanel10.add(btnDelete);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 245, 280, 100, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadPending());
        jPanel10.add(btnRefresh);
        
        setupSearch(txtSearch, sorterPending, btnClear);
    }

    private void approveUser() {
        int row = tblPending.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int userId = (int) modelPending.getValueAt(row, 0);
        String username = (String) modelPending.getValueAt(row, 1);
        
        int conf = JOptionPane.showConfirmDialog(this, "Approve " + username + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            try {
                config cfg = new config();
                Connection conn = cfg.connectDB();
                
                String sql = "UPDATE users SET status = 'approved' WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, userId);
                pstmt.executeUpdate();
                pstmt.close();
                conn.close();
                
                JOptionPane.showMessageDialog(this, "User approved!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadPending();
                loadUsers();
                loadDashboardStats();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void deleteUser() {
      int row = tblPending.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int userId = (int) modelPending.getValueAt(row, 0);
        String username = (String) modelPending.getValueAt(row, 1);
        
        int conf = JOptionPane.showConfirmDialog(this, "DELETE " + username + "?\nThis cannot be undone!", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (conf == JOptionPane.YES_OPTION) {
            try {
                config cfg = new config();
                Connection conn = cfg.connectDB();
                
                String sql = "DELETE FROM users WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, userId);
                pstmt.executeUpdate();
                pstmt.close();
                conn.close();
                
                JOptionPane.showMessageDialog(this, "User deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadPending();
                loadDashboardStats();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }


}

   
