/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import config.config;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author Dell
 */
public class ClientDashboard extends javax.swing.JFrame {
     private String loggedInUsername;
    private int clientId;
    private DefaultTableModel modelProjects;
    private DefaultTableModel modelContractors;
    private JTable tblProjects;
    private JTable tblContractors;
    private TableRowSorter<DefaultTableModel> sorterProjects;
    private TableRowSorter<DefaultTableModel> sorterContractors;
    private JLabel lblTotalProjects;
    private JLabel lblActiveProjects;
    private JLabel lblTotalSpent;
    private JLabel lblCompletedProjects;

    /**
     * Creates new form ClientDashboard
     */
    public ClientDashboard(String username) {
         this.loggedInUsername = username;
        initComponents();
        getClientId();
        jLabel2.setText("WELCOME, " + username.toUpperCase());
        setupAllTabs();
        loadDashboardStats();
        loadMyProjects();
        loadContractors();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CLIENT DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("WELCOME, CLIENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 130));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText(" My Profile");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText(" Dashboard ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("  My Projects   ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 30));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText(" View Contractors ");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 30));

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText(" Create Project ");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 30));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("💰 Make Payment");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 430));

        jTabbedPane1.addTab("tab1", jPanel3);
        jTabbedPane1.addTab("tab2", jPanel4);
        jTabbedPane1.addTab("tab3", jPanel5);
        jTabbedPane1.addTab("tab4", jPanel6);
        jTabbedPane1.addTab("tab5", jPanel7);
        jTabbedPane1.addTab("tab6", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 490, 430));

        setSize(new java.awt.Dimension(672, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jTabbedPane1.setSelectedIndex(3);
        loadContractors();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jTabbedPane1.setSelectedIndex(1);
        loadDashboardStats();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jTabbedPane1.setSelectedIndex(2);
        loadMyProjects();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         createProject();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         int confirm = JOptionPane.showConfirmDialog(this, "Logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login.Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        makePayment();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new ClientDashboard("testclient").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void getClientId() {
        try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            String sql = "SELECT id FROM users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, loggedInUsername);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) clientId = rs.getInt("id");
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   private void setupAllTabs() {
        setupProfileTab();
        setupDashboardTab();
        setupProjectsTab();
        setupContractorsTab();
    }

    private void loadDashboardStats() {
         try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            PreparedStatement p1 = conn.prepareStatement("SELECT COUNT(*) as c FROM projects WHERE client_id = ?");
            p1.setInt(1, clientId);
            ResultSet r1 = p1.executeQuery();
            if (r1.next()) lblTotalProjects.setText(String.valueOf(r1.getInt("c")));
            r1.close(); p1.close();
            
            PreparedStatement p2 = conn.prepareStatement("SELECT COUNT(*) as c FROM projects WHERE client_id = ? AND status = 'In Progress'");
            p2.setInt(1, clientId);
            ResultSet r2 = p2.executeQuery();
            if (r2.next()) lblActiveProjects.setText(String.valueOf(r2.getInt("c")));
            r2.close(); p2.close();
            
            PreparedStatement p3 = conn.prepareStatement("SELECT SUM(amount) as t FROM payments WHERE project_id IN (SELECT id FROM projects WHERE client_id = ?)");
            p3.setInt(1, clientId);
            ResultSet r3 = p3.executeQuery();
            if (r3.next()) lblTotalSpent.setText("₱" + String.format("%.2f", r3.getDouble("t")));
            r3.close(); p3.close();
            
            PreparedStatement p4 = conn.prepareStatement("SELECT COUNT(*) as c FROM projects WHERE client_id = ? AND status = 'Completed'");
            p4.setInt(1, clientId);
            ResultSet r4 = p4.executeQuery();
            if (r4.next()) lblCompletedProjects.setText(String.valueOf(r4.getInt("c")));
            r4.close(); p4.close();
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadMyProjects() {
         try {
            modelProjects.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT p.id, p.project_name, COALESCE(u.username, 'Not Assigned') as contractor, p.budget, p.status FROM projects p LEFT JOIN users u ON p.contractor_id = u.id WHERE p.client_id = ? ORDER BY p.id DESC";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, clientId);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                modelProjects.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    rs.getString("contractor"),
                    "₱" + String.format("%.2f", rs.getDouble("budget")),
                    rs.getString("status")
                });
            }
            
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadContractors() {
         try {
            modelContractors.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT id, username, status FROM users WHERE role = 'contractor' AND status = 'approved' ORDER BY id";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                modelContractors.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("status").toUpperCase()
                });
            }
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createProject() {
        JPanel panel = new JPanel(new GridLayout(3, 2, 10, 10));
        
        JTextField txtName = new JTextField();
        JTextField txtDesc = new JTextField();
        JTextField txtBudget = new JTextField();
        
        panel.add(new JLabel("Project Name:"));
        panel.add(txtName);
        panel.add(new JLabel("Description:"));
        panel.add(txtDesc);
        panel.add(new JLabel("Budget (₱):"));
        panel.add(txtBudget);
        
        int result = JOptionPane.showConfirmDialog(this, panel, "Create New Project", JOptionPane.OK_CANCEL_OPTION);
        
        if (result == JOptionPane.OK_OPTION) {
            String name = txtName.getText().trim();
            String desc = txtDesc.getText().trim();
            String budgetStr = txtBudget.getText().trim();
            
            if (name.isEmpty() || budgetStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                double budget = Double.parseDouble(budgetStr);
                
                config cfg = new config();
                Connection conn = cfg.connectDB();
                
                String sql = "INSERT INTO projects (project_name, description, budget, client_id, status) VALUES (?, ?, ?, ?, 'Open')";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, name);
                pstmt.setString(2, desc);
                pstmt.setDouble(3, budget);
                pstmt.setInt(4, clientId);
                pstmt.executeUpdate();
                pstmt.close();
                conn.close();
                
                JOptionPane.showMessageDialog(this, "Project created!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadMyProjects();
                loadDashboardStats();
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid budget!", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void setupProfileTab() {
        jPanel3.setLayout(null);
        jPanel3.setBackground(new Color(245, 247, 250));
        
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBounds(60, 30, 350, 320);
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        
        JPanel avatar = new JPanel();
        avatar.setBounds(125, 20, 100, 100);
        avatar.setBackground(new Color(34, 197, 94));
        avatar.setLayout(new BorderLayout());
        JLabel avatarLbl = new JLabel("👤", SwingConstants.CENTER);
        avatarLbl.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 50));
        avatarLbl.setForeground(Color.WHITE);
        avatar.add(avatarLbl);
        card.add(avatar);
        
        JLabel lblName = new JLabel(loggedInUsername.toUpperCase(), SwingConstants.CENTER);
        lblName.setBounds(25, 130, 300, 35);
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 24));
        card.add(lblName);
        
        JLabel lblRole = new JLabel("CLIENT", SwingConstants.CENTER);
        lblRole.setBounds(100, 170, 150, 30);
        lblRole.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblRole.setForeground(Color.WHITE);
        lblRole.setBackground(new Color(59, 130, 246));
        lblRole.setOpaque(true);
        card.add(lblRole);
        
        JLabel lblId = new JLabel("User ID: " + clientId);
        lblId.setBounds(25, 230, 300, 25);
        lblId.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        card.add(lblId);
        
        JLabel lblStatus = new JLabel("● Active");
        lblStatus.setBounds(25, 260, 300, 25);
        lblStatus.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblStatus.setForeground(new Color(34, 197, 94));
        card.add(lblStatus);
        
        jPanel3.add(card);
    }

    private void setupDashboardTab() {
         jPanel4.setLayout(null);
        jPanel4.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("DASHBOARD OVERVIEW");
        title.setFont(new Font("Segoe UI", Font.BOLD, 22));
        title.setBounds(20, 15, 400, 30);
        jPanel4.add(title);
        
        JPanel c1 = createCard("📊 Total Projects", "0", 20, 60, new Color(59, 130, 246));
        JPanel c2 = createCard("⚡ Active", "0", 260, 60, new Color(34, 197, 94));
        JPanel c3 = createCard("💰 Total Spent", "₱0.00", 20, 210, new Color(251, 146, 60));
        JPanel c4 = createCard("✅ Completed", "0", 260, 210, new Color(168, 85, 247));
        
        jPanel4.add(c1);
        jPanel4.add(c2);
        jPanel4.add(c3);
        jPanel4.add(c4);
    }


    private void setupProjectsTab() {
       jPanel5.setLayout(null);
        jPanel5.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("📁 MY PROJECTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel5.add(title);
        
        JTextField txtSearch = new JTextField();
        txtSearch.setBounds(45, 50, 280, 30);
        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtSearch.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPanel5.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel5.add(searchIcon);
        
        JButton btnClear = new JButton("✕");
        btnClear.setBounds(335, 50, 50, 30);
        btnClear.setBackground(Color.WHITE);
        btnClear.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btnClear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        jPanel5.add(btnClear);
        
        String[] cols = {"ID", "Project", "Contractor", "Budget", "Status"};
        modelProjects = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblProjects = new JTable(modelProjects);
        tblProjects.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tblProjects.setRowHeight(28);
        tblProjects.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblProjects.setSelectionBackground(new Color(219, 234, 254));
        
        sorterProjects = new TableRowSorter<>(modelProjects);
        tblProjects.setRowSorter(sorterProjects);
        
        JScrollPane sp = new JScrollPane(tblProjects);
        sp.setBounds(15, 90, 455, 140);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel5.add(sp);
        
        JButton btnPay = createBtn("💰 PAY", 15, 240, 100, 35, new Color(59, 130, 246));
        btnPay.addActionListener(e -> makePayment());
        jPanel5.add(btnPay);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 125, 240, 110, 35, new Color(168, 85, 247));
        btnRefresh.addActionListener(e -> loadMyProjects());
        jPanel5.add(btnRefresh);
        
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorterProjects.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorterProjects.setRowFilter(null);
        });
    }


    private void setupContractorsTab() {
        jPanel6.setLayout(null);
        jPanel6.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("🔧 AVAILABLE CONTRACTORS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 400, 30);
        jPanel6.add(title);
        
        JTextField txtSearch = new JTextField();
        txtSearch.setBounds(45, 50, 300, 30);
        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtSearch.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPanel6.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel6.add(searchIcon);
        
        JButton btnClear = new JButton("✕");
        btnClear.setBounds(355, 50, 50, 30);
        btnClear.setBackground(Color.WHITE);
        btnClear.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btnClear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        jPanel6.add(btnClear);
        
        String[] cols = {"ID", "Username", "Status"};
        modelContractors = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblContractors = new JTable(modelContractors);
        tblContractors.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblContractors.setRowHeight(30);
        tblContractors.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblContractors.setSelectionBackground(new Color(219, 234, 254));
        
        sorterContractors = new TableRowSorter<>(modelContractors);
        tblContractors.setRowSorter(sorterContractors);
        
        JScrollPane sp = new JScrollPane(tblContractors);
        sp.setBounds(15, 90, 455, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel6.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 110, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadContractors());
        jPanel6.add(btnRefresh);
        
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorterContractors.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorterContractors.setRowFilter(null);
        });
    }


     private JPanel createCard(String title, String value, int x, int y, Color color) {
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBounds(x, y, 210, 130);
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        
        JPanel bar = new JPanel();
        bar.setBounds(0, 0, 5, 130);
        bar.setBackground(color);
        card.add(bar);
        
        JLabel lbl1 = new JLabel(title);
        lbl1.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lbl1.setForeground(new Color(100, 116, 139));
        lbl1.setBounds(15, 15, 190, 20);
        card.add(lbl1);
        
        JLabel lbl2 = new JLabel(value);
        lbl2.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lbl2.setBounds(15, 60, 190, 40);
        card.add(lbl2);
        
        if (title.contains("Total Projects")) lblTotalProjects = lbl2;
        else if (title.contains("Active")) lblActiveProjects = lbl2;
        else if (title.contains("Spent")) lblTotalSpent = lbl2;
        else if (title.contains("Completed")) lblCompletedProjects = lbl2;
        
        return card;
    }

      private JButton createBtn(String text, int x, int y, int w, int h, Color bg) {
        JButton btn = new JButton(text);
        btn.setBounds(x, y, w, h);
        btn.setBackground(bg);
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setFocusPainted(false);
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(bg.darker());
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(bg);
            }
        });
        return btn;
    }

    private void makePayment() {
      int row = tblProjects.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a project first!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int projectId = (int) modelProjects.getValueAt(row, 0);
    String projectName = (String) modelProjects.getValueAt(row, 1);
    
    String amountStr = JOptionPane.showInputDialog(this, "Enter amount for: " + projectName, "Make Payment", JOptionPane.PLAIN_MESSAGE);
    
    if (amountStr != null && !amountStr.trim().isEmpty()) {
        try {
            double amount = Double.parseDouble(amountStr);
            
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "INSERT INTO payments (project_id, amount, payment_date, status) VALUES (?, ?, date('now'), 'Paid')";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, projectId);
            pstmt.setDouble(2, amount);
            pstmt.executeUpdate();
            pstmt.close();
            conn.close();
            
            JOptionPane.showMessageDialog(this, "Payment of ₱" + String.format("%.2f", amount) + " recorded!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadDashboardStats();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}



}
