/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import config.config;
import config.SessionManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.io.File;
import java.sql.*;
/**
 *
 * @author Dell
 */
public class ContractorDashboard extends javax.swing.JFrame {
     private String loggedInUsername;
    private int contractorId;
    private DefaultTableModel modelAvailableProjects;
    private DefaultTableModel modelMyProjects;
    private DefaultTableModel modelPayments;
    private JTable tblAvailableProjects;
    private JTable tblMyProjects;
    private JTable tblPayments;
    private TableRowSorter<DefaultTableModel> sorterAvailable;
    private TableRowSorter<DefaultTableModel> sorterMyProjects;
    private TableRowSorter<DefaultTableModel> sorterPayments;
    private JLabel lblTotalProjects;
    private JLabel lblActiveProjects;
    private JLabel lblTotalEarnings;
    private JLabel lblPendingPayments;
    private String bio;
    private Object[] clientId;

   

    /**
     * Creates new form ContractorDasboard
     */
   public ContractorDashboard(String username) {
    SessionManager session = SessionManager.getInstance();
        
        if (!session.isLoggedIn() || !session.validateSession("contractor")) {
            JOptionPane.showMessageDialog(null,
                "❌ Unauthorized Access!\n\nPlease login first.",
                "Security Alert",
                JOptionPane.ERROR_MESSAGE);
            
            this.dispose();
            new Login.Login().setVisible(true);
            return;
        }
        
        this.loggedInUsername = username;
        initComponents();
        
        // ✅ ADD WINDOW LISTENER
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                SessionManager.getInstance().logout();
                System.exit(0);
            }
        });
        
        getContractorId();
        jLabel2.setText("WELCOME, " + username.toUpperCase());
        setupAllTabs();
        loadDashboardStats();
        loadAvailableProjects();
        loadMyProjects();
        loadMyPayments();
    }


    private ContractorDashboard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CONTRACTOR DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME, CONTRACTOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 130));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("👤 My Profile    ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText(" 📊 Dashboard  ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText(" 📁 My Projects     ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("💰 My Payments");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 30));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("🔍 Browse Projects ");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 400));

        jTabbedPane1.addTab("tab1", jPanel3);
        jTabbedPane1.addTab("tab2", jPanel4);
        jTabbedPane1.addTab("tab3", jPanel5);
        jTabbedPane1.addTab("tab4", jPanel6);
        jTabbedPane1.addTab("tab5", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 480, 430));

        setSize(new java.awt.Dimension(666, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jTabbedPane1.setSelectedIndex(4);
        loadMyPayments();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        loadDashboardStats();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTabbedPane1.setSelectedIndex(3);
        loadMyProjects();
    }//GEN-LAST:event_jButton3ActionPerformed
   
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, "Logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION) {
            // ✅ DESTROY SESSION
            SessionManager.getInstance().logout();
            
            this.dispose();
            new Login.Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jTabbedPane1.setSelectedIndex(2);
        loadAvailableProjects();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new ContractorDashboard("testuser").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void getContractorId() {
       try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            String sql = "SELECT id FROM users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, loggedInUsername);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) contractorId = rs.getInt("id");
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void setupAllTabs() {
        setupProfileTab();
        setupDashboardTab();
        setupAvailableProjectsTab();
        setupMyProjectsTab();
        setupPaymentsTab();
    }

    private void loadDashboardStats() {
        try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            PreparedStatement p1 = conn.prepareStatement("SELECT COUNT(*) as c FROM projects WHERE contractor_id = ?");
            p1.setInt(1, contractorId);
            ResultSet r1 = p1.executeQuery();
            if (r1.next()) lblTotalProjects.setText(String.valueOf(r1.getInt("c")));
            r1.close(); p1.close();
            
            PreparedStatement p2 = conn.prepareStatement("SELECT COUNT(*) as c FROM projects WHERE contractor_id = ? AND status = 'In Progress'");
            p2.setInt(1, contractorId);
            ResultSet r2 = p2.executeQuery();
            if (r2.next()) lblActiveProjects.setText(String.valueOf(r2.getInt("c")));
            r2.close(); p2.close();
            
            PreparedStatement p3 = conn.prepareStatement("SELECT SUM(pay.amount) as t FROM payments pay JOIN projects p ON pay.project_id = p.id WHERE p.contractor_id = ?");
            p3.setInt(1, contractorId);
            ResultSet r3 = p3.executeQuery();
            if (r3.next()) lblTotalEarnings.setText("₱" + String.format("%.2f", r3.getDouble("t")));
            r3.close(); p3.close();
            
            PreparedStatement p4 = conn.prepareStatement("SELECT SUM(p.budget - COALESCE(t.tot, 0)) as pend FROM projects p LEFT JOIN (SELECT project_id, SUM(amount) as tot FROM payments GROUP BY project_id) t ON p.id = t.project_id WHERE p.contractor_id = ? AND p.status = 'In Progress'");
            p4.setInt(1, contractorId);
            ResultSet r4 = p4.executeQuery();
            if (r4.next()) lblPendingPayments.setText("₱" + String.format("%.2f", r4.getDouble("pend")));
            r4.close(); p4.close();
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadAvailableProjects() {
         try {
            modelAvailableProjects.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT p.id, p.project_name, u.username as client, p.budget, p.status FROM projects p JOIN users u ON p.client_id = u.id WHERE p.status = 'Open' ORDER BY p.id DESC";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                modelAvailableProjects.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    rs.getString("client"),
                    "₱" + String.format("%.2f", rs.getDouble("budget")),
                    rs.getString("status")
                });
            }
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadMyProjects() {
         try {
            modelMyProjects.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT p.id, p.project_name, u.username as client, p.budget, p.status FROM projects p JOIN users u ON p.client_id = u.id WHERE p.contractor_id = ? ORDER BY p.id DESC";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, contractorId);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                modelMyProjects.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    rs.getString("client"),
                    "₱" + String.format("%.2f", rs.getDouble("budget")),
                    rs.getString("status")
                });
            }
            
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadMyPayments() {
        try {
            modelPayments.setRowCount(0);
            config cfg = new config();
            Connection conn = cfg.connectDB();
            
            String sql = "SELECT pay.id, p.project_name, pay.amount, pay.payment_date, pay.status FROM payments pay JOIN projects p ON pay.project_id = p.id WHERE p.contractor_id = ? ORDER BY pay.id DESC";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, contractorId);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                modelPayments.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("project_name"),
                    "₱" + String.format("%.2f", rs.getDouble("amount")),
                    rs.getString("payment_date"),
                    rs.getString("status")
                });
            }
            
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setupProfileTab() {
     jPanel3.setLayout(null);
    jPanel3.setBackground(new Color(245, 247, 250));
    
    // ✅ GET DATA FIRST
    String currentBio = (String) getBio();
    String currentEmail = getEmail();
    String currentPic = getProfilePic();
    
    // ═══ SCROLL PANEL ═══
    JPanel mainPanel = new JPanel();
    mainPanel.setLayout(null);
    mainPanel.setBackground(new Color(245, 247, 250));
    mainPanel.setPreferredSize(new Dimension(460, 700));
    
    JScrollPane mainScroll = new JScrollPane(mainPanel);
    mainScroll.setBounds(0, 0, 475, 420);
    mainScroll.setBorder(null);
    mainScroll.getVerticalScrollBar().setUnitIncrement(16);
    jPanel3.add(mainScroll);
    
    // ═══ PROFILE CARD ═══
    JPanel card = new JPanel();
    card.setLayout(null);
    card.setBounds(10, 10, 440, 660);
    card.setBackground(Color.WHITE);
    card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
    mainPanel.add(card);
    
    // ═══ HEADER ═══
    JPanel headerBar = new JPanel();
    headerBar.setLayout(null);
    headerBar.setBounds(0, 0, 440, 35);
    headerBar.setBackground(new Color(37, 99, 235));  // ✅ BLUE
    card.add(headerBar);
    
    JLabel headerTitle = new JLabel("👤  MY PROFILE");
    headerTitle.setBounds(15, 5, 300, 25);
    headerTitle.setFont(new Font("Segoe UI", Font.BOLD, 14));
    headerTitle.setForeground(Color.WHITE);
    headerBar.add(headerTitle);
    
    // ═══ AVATAR ═══
    JPanel avatar = new JPanel();
    avatar.setBounds(20, 50, 90, 90);
    avatar.setBackground(new Color(37, 99, 235));  // ✅ BLUE
    avatar.setLayout(new BorderLayout());
    
    File picFile = new File(currentPic.isEmpty() ? "nofile" : currentPic);
    if (!currentPic.isEmpty() && picFile.exists()) {
        try {
            java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(picFile);
            java.awt.Image scaled = img.getScaledInstance(90, 90, java.awt.Image.SCALE_SMOOTH);
            avatar.add(new JLabel(new ImageIcon(scaled)));
        } catch (Exception e) {
            addDefaultAvatar(avatar);
        }
    } else {
        addDefaultAvatar(avatar);
    }
    card.add(avatar);
    
    // ═══ CHANGE PHOTO ═══
    JButton btnPhoto = new JButton("📷 Change");
    btnPhoto.setBounds(20, 145, 90, 22);
    btnPhoto.setFont(new Font("Segoe UI", Font.PLAIN, 9));
    btnPhoto.setBackground(new Color(241, 245, 249));
    btnPhoto.setForeground(new Color(71, 85, 105));
    btnPhoto.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 1));
    btnPhoto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnPhoto.setFocusPainted(false);
    btnPhoto.addActionListener(e -> {
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Images (*.jpg, *.png)", "jpg", "jpeg", "png"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            saveProfilePic(fc.getSelectedFile().getAbsolutePath());
            jPanel3.removeAll();
            setupProfileTab();
            jPanel3.revalidate();
            jPanel3.repaint();
        }
    });
    card.add(btnPhoto);
    
    // ═══ USERNAME ═══
    JLabel lblNameTitle = new JLabel("Username");
    lblNameTitle.setBounds(125, 50, 200, 15);
    lblNameTitle.setFont(new Font("Segoe UI", Font.PLAIN, 11));
    lblNameTitle.setForeground(new Color(148, 163, 184));
    card.add(lblNameTitle);
    
    JLabel lblName = new JLabel(loggedInUsername.toUpperCase());
    lblName.setBounds(125, 65, 300, 28);
    lblName.setFont(new Font("Segoe UI", Font.BOLD, 20));
    lblName.setForeground(new Color(30, 41, 59));
    card.add(lblName);
    
    // ═══ ROLE BADGE ═══
 JLabel lblRole = new JLabel("CONTRACTOR", SwingConstants.CENTER);
lblRole.setBounds(125, 96, 110, 22);
    lblRole.setFont(new Font("Segoe UI", Font.BOLD, 11));
    lblRole.setForeground(Color.WHITE);
    lblRole.setBackground(new Color(37, 99, 235));  // ✅ BLUE
    lblRole.setOpaque(true);
    card.add(lblRole);
    
    // ═══ SEPARATOR ═══
    JSeparator sep1 = new JSeparator();
    sep1.setBounds(15, 175, 410, 2);
    sep1.setForeground(new Color(241, 245, 249));
    card.add(sep1);
    
    // ═══ USER ID ═══
    JLabel lblIdTitle = new JLabel("👤  User ID:");
    lblIdTitle.setBounds(15, 183, 120, 20);
    lblIdTitle.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblIdTitle.setForeground(new Color(100, 116, 139));
    card.add(lblIdTitle);
    
   JLabel lblId = new JLabel("#" + String.format("%03d", contractorId));
    lblId.setBounds(140, 183, 200, 20);
    lblId.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblId.setForeground(new Color(30, 41, 59));
    card.add(lblId);
    
    // ═══ EMAIL ═══
    JLabel lblEmailTitle = new JLabel("✉️  Email:");
    lblEmailTitle.setBounds(15, 208, 120, 20);
    lblEmailTitle.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblEmailTitle.setForeground(new Color(100, 116, 139));
    card.add(lblEmailTitle);
    
    JLabel lblEmail = new JLabel(currentEmail.isEmpty() ? "Not set" : currentEmail);
    lblEmail.setBounds(140, 208, 285, 20);
    lblEmail.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    lblEmail.setForeground(new Color(30, 41, 59));
    card.add(lblEmail);
    
    // ═══ STATUS ═══
    JLabel lblStatusTitle = new JLabel("🟢  Status:");
    lblStatusTitle.setBounds(15, 233, 120, 20);
    lblStatusTitle.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblStatusTitle.setForeground(new Color(100, 116, 139));
    card.add(lblStatusTitle);
    
    JLabel lblStatus = new JLabel("● Active");
    lblStatus.setBounds(140, 233, 285, 20);
    lblStatus.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblStatus.setForeground(new Color(34, 197, 94));
    card.add(lblStatus);
    
    // ═══ SEPARATOR ═══
    JSeparator sep2 = new JSeparator();
    sep2.setBounds(15, 260, 410, 2);
    sep2.setForeground(new Color(241, 245, 249));
    card.add(sep2);
    
    // ═══ BIO SECTION ═══
    JPanel bioHeader = new JPanel();
    bioHeader.setLayout(null);
    bioHeader.setBounds(15, 268, 410, 25);
    bioHeader.setBackground(Color.WHITE);
    card.add(bioHeader);
    
    JLabel lblBioTitle = new JLabel("📝  Bio");
    lblBioTitle.setBounds(0, 0, 200, 25);
    lblBioTitle.setFont(new Font("Segoe UI", Font.BOLD, 13));
    lblBioTitle.setForeground(new Color(30, 41, 59));
    bioHeader.add(lblBioTitle);
    
    JLabel lblCharCount = new JLabel(currentBio.length() + "/200");
    lblCharCount.setBounds(355, 0, 55, 25);
    lblCharCount.setFont(new Font("Segoe UI", Font.PLAIN, 11));
    lblCharCount.setForeground(new Color(148, 163, 184));
    bioHeader.add(lblCharCount);
    
    JTextArea txtBio = new JTextArea();
    txtBio.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    txtBio.setLineWrap(true);
    txtBio.setWrapStyleWord(true);
    txtBio.setText(currentBio);
    txtBio.setForeground(new Color(30, 41, 59));
    txtBio.setBorder(BorderFactory.createEmptyBorder(8, 10, 8, 10));
    txtBio.setBackground(new Color(248, 250, 252));
    
    txtBio.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { update(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { update(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { update(); }
        void update() {
            int count = txtBio.getText().length();
            lblCharCount.setText(count + "/200");
            if (count > 200) {
                SwingUtilities.invokeLater(() ->
                    txtBio.setText(txtBio.getText().substring(0, 200)));
            }
        }
    });
    
    JScrollPane bioScroll = new JScrollPane(txtBio);
    bioScroll.setBounds(15, 295, 410, 80);
    bioScroll.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 1));
    card.add(bioScroll);
    
    // ═══ SAVE PROFILE BUTTON ═══
    JButton btnSave = new JButton("💾  SAVE PROFILE");
    btnSave.setBounds(15, 385, 410, 38);
    btnSave.setFont(new Font("Segoe UI", Font.BOLD, 14));
    btnSave.setBackground(new Color(37, 99, 235));  // ✅ BLUE
    btnSave.setForeground(Color.WHITE);
    btnSave.setBorderPainted(false);
    btnSave.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnSave.setFocusPainted(false);
    btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent e) {
            btnSave.setBackground(new Color(29, 78, 216));
        }
        public void mouseExited(java.awt.event.MouseEvent e) {
            btnSave.setBackground(new Color(37, 99, 235));
        }
    });
    btnSave.addActionListener(e -> {
        saveBio(txtBio.getText().trim());
        JOptionPane.showMessageDialog(this,
            "✅ Profile saved successfully!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
        jPanel3.removeAll();
        setupProfileTab();
        jPanel3.revalidate();
        jPanel3.repaint();
    });
    card.add(btnSave);
    
    // ═══ SEPARATOR ═══
    JSeparator sep3 = new JSeparator();
    sep3.setBounds(15, 435, 410, 2);
    sep3.setForeground(new Color(241, 245, 249));
    card.add(sep3);
    
    // ═══ PASSWORD SECTION HEADER ═══
    JPanel pwHeader = new JPanel();
    pwHeader.setLayout(null);
    pwHeader.setBounds(0, 438, 440, 35);
    pwHeader.setBackground(new Color(51, 65, 85));
    card.add(pwHeader);
    
    JLabel pwTitle = new JLabel("🔒  CHANGE PASSWORD");
    pwTitle.setBounds(15, 5, 300, 25);
    pwTitle.setFont(new Font("Segoe UI", Font.BOLD, 14));
    pwTitle.setForeground(Color.WHITE);
    pwHeader.add(pwTitle);
    
    // Current Password
    JLabel lblCurrent = new JLabel("Current Password:");
    lblCurrent.setBounds(15, 483, 150, 20);
    lblCurrent.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblCurrent.setForeground(new Color(100, 116, 139));
    card.add(lblCurrent);
    
    JPasswordField txtCurrent = new JPasswordField();
    txtCurrent.setBounds(170, 483, 255, 28);
    txtCurrent.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    txtCurrent.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(203, 213, 225), 1),
        BorderFactory.createEmptyBorder(5, 8, 5, 8)));
    card.add(txtCurrent);
    
    // New Password
    JLabel lblNew = new JLabel("New Password:");
    lblNew.setBounds(15, 520, 150, 20);
    lblNew.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblNew.setForeground(new Color(100, 116, 139));
    card.add(lblNew);
    
    JPasswordField txtNew = new JPasswordField();
    txtNew.setBounds(170, 520, 255, 28);
    txtNew.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    txtNew.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(203, 213, 225), 1),
        BorderFactory.createEmptyBorder(5, 8, 5, 8)));
    card.add(txtNew);
    
    // Confirm Password
    JLabel lblConfirm = new JLabel("Confirm Password:");
    lblConfirm.setBounds(15, 557, 150, 20);
    lblConfirm.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblConfirm.setForeground(new Color(100, 116, 139));
    card.add(lblConfirm);
    
    JPasswordField txtConfirm = new JPasswordField();
    txtConfirm.setBounds(170, 557, 255, 28);
    txtConfirm.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    txtConfirm.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(203, 213, 225), 1),
        BorderFactory.createEmptyBorder(5, 8, 5, 8)));
    card.add(txtConfirm);
    
    // Strength Indicator
    JLabel lblStrength = new JLabel("");
    lblStrength.setBounds(170, 590, 255, 18);
    lblStrength.setFont(new Font("Segoe UI", Font.BOLD, 11));
    card.add(lblStrength);
    
    txtNew.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { update(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { update(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { update(); }
        void update() {
            String pw = new String(txtNew.getPassword());
            if (pw.isEmpty()) {
                lblStrength.setText("");
            } else if (pw.length() < 6) {
                lblStrength.setText("🔴 Weak");
                lblStrength.setForeground(new Color(220, 38, 38));
            } else if (pw.length() < 10) {
                lblStrength.setText("🟡 Medium");
                lblStrength.setForeground(new Color(234, 179, 8));
            } else {
                lblStrength.setText("🟢 Strong");
                lblStrength.setForeground(new Color(34, 197, 94));
            }
        }
    });
    
    // ═══ CHANGE PASSWORD BUTTON ═══
    JButton btnChangePw = new JButton("🔒  CHANGE PASSWORD");
    btnChangePw.setBounds(15, 615, 410, 38);
    btnChangePw.setFont(new Font("Segoe UI", Font.BOLD, 14));
    btnChangePw.setBackground(new Color(51, 65, 85));
    btnChangePw.setForeground(Color.WHITE);
    btnChangePw.setBorderPainted(false);
    btnChangePw.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnChangePw.setFocusPainted(false);
    btnChangePw.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent e) {
            btnChangePw.setBackground(new Color(30, 41, 59));
        }
        public void mouseExited(java.awt.event.MouseEvent e) {
            btnChangePw.setBackground(new Color(51, 65, 85));
        }
    });
    btnChangePw.addActionListener(e -> {
        String current = new String(txtCurrent.getPassword()).trim();
        String newPw = new String(txtNew.getPassword()).trim();
        String confirm = new String(txtConfirm.getPassword()).trim();
        
        if (current.isEmpty() || newPw.isEmpty() || confirm.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "⚠️ All password fields are required!",
                "Missing Fields",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (newPw.length() < 6) {
            JOptionPane.showMessageDialog(this,
                "❌ New password must be at least 6 characters!",
                "Too Short",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!newPw.equals(confirm)) {
            JOptionPane.showMessageDialog(this,
                "❌ Passwords do not match!\n\nPlease re-enter.",
                "Mismatch",
                JOptionPane.ERROR_MESSAGE);
            txtNew.setText("");
            txtConfirm.setText("");
            txtNew.requestFocus();
            return;
        }
        
        if (!verifyCurrentPassword(current)) {
            JOptionPane.showMessageDialog(this,
                "❌ Current password is incorrect!",
                "Wrong Password",
                JOptionPane.ERROR_MESSAGE);
            txtCurrent.setText("");
            txtCurrent.requestFocus();
            return;
        }
        
        if (current.equals(newPw)) {
            JOptionPane.showMessageDialog(this,
                "❌ New password cannot be\nsame as current password!",
                "Same Password",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (changePassword(newPw)) {
            JOptionPane.showMessageDialog(this,
                "✅ Password changed successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            txtCurrent.setText("");
            txtNew.setText("");
            txtConfirm.setText("");
            lblStrength.setText("");
        }
    });
    card.add(btnChangePw);
    }

    private void setupDashboardTab() {
        jPanel4.setLayout(null);
        jPanel4.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("DASHBOARD OVERVIEW");
        title.setFont(new Font("Segoe UI", Font.BOLD, 22));
        title.setBounds(20, 15, 400, 30);
        jPanel4.add(title);
        
        JPanel c1 = createCard("📊 Total Projects", "0", 20, 60, new Color(59, 130, 246));
        JPanel c2 = createCard("⚡ Active", "0", 250, 60, new Color(34, 197, 94));
        JPanel c3 = createCard("💰 Earnings", "₱0.00", 20, 210, new Color(251, 146, 60));
        JPanel c4 = createCard("⏳ Pending", "₱0.00", 250, 210, new Color(168, 85, 247));
        
        jPanel4.add(c1);
        jPanel4.add(c2);
        jPanel4.add(c3);
        jPanel4.add(c4);
    }
    private void setupAvailableProjectsTab() {
         jPanel5.setLayout(null);
        jPanel5.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("🔍 BROWSE PROJECTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel5.add(title);
        
        JTextField txtSearch = new JTextField();
        txtSearch.setBounds(45, 50, 280, 30);
        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtSearch.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPanel5.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel5.add(searchIcon);
        
        JButton btnClear = new JButton("✕");
        btnClear.setBounds(335, 50, 50, 30);
        btnClear.setBackground(Color.WHITE);
        btnClear.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btnClear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        jPanel5.add(btnClear);
        
        String[] cols = {"ID", "Project", "Client", "Budget", "Status"};
        modelAvailableProjects = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblAvailableProjects = new JTable(modelAvailableProjects);
        tblAvailableProjects.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tblAvailableProjects.setRowHeight(28);
        tblAvailableProjects.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblAvailableProjects.setSelectionBackground(new Color(219, 234, 254));
        
        sorterAvailable = new TableRowSorter<>(modelAvailableProjects);
        tblAvailableProjects.setRowSorter(sorterAvailable);
        
        JScrollPane sp = new JScrollPane(tblAvailableProjects);
        sp.setBounds(15, 90, 445, 180);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel5.add(sp);
        
        JButton btnAccept = createBtn("✓ ACCEPT", 15, 280, 130, 35, new Color(34, 197, 94));
        btnAccept.addActionListener(e -> acceptProject());
        jPanel5.add(btnAccept);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 155, 280, 110, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadAvailableProjects());
        jPanel5.add(btnRefresh);
        
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorterAvailable.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorterAvailable.setRowFilter(null);
        });
    }

    private void setupMyProjectsTab() {
        jPanel6.setLayout(null);
        jPanel6.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("📁 MY PROJECTS");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel6.add(title);
        
        JTextField txtSearch = new JTextField();
        txtSearch.setBounds(45, 50, 280, 30);
        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtSearch.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPanel6.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel6.add(searchIcon);
        
        JButton btnClear = new JButton("✕");
        btnClear.setBounds(335, 50, 50, 30);
        btnClear.setBackground(Color.WHITE);
        btnClear.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btnClear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        jPanel6.add(btnClear);
        
        String[] cols = {"ID", "Project", "Client", "Budget", "Status"};
        modelMyProjects = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblMyProjects = new JTable(modelMyProjects);
        tblMyProjects.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tblMyProjects.setRowHeight(28);
        tblMyProjects.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblMyProjects.setSelectionBackground(new Color(219, 234, 254));
        
        sorterMyProjects = new TableRowSorter<>(modelMyProjects);
        tblMyProjects.setRowSorter(sorterMyProjects);
        
        JScrollPane sp = new JScrollPane(tblMyProjects);
        sp.setBounds(15, 90, 445, 180);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel6.add(sp);
        
        JButton btnComplete = createBtn("✓ COMPLETE", 15, 280, 130, 35, new Color(34, 197, 94));
        btnComplete.addActionListener(e -> markComplete());
        jPanel6.add(btnComplete);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 155, 280, 110, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadMyProjects());
        jPanel6.add(btnRefresh);
        
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorterMyProjects.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorterMyProjects.setRowFilter(null);
        });
    }

    private void setupPaymentsTab() {
         jPanel7.setLayout(null);
        jPanel7.setBackground(new Color(245, 247, 250));
        
        JLabel title = new JLabel("💰 PAYMENT HISTORY");
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBounds(15, 10, 300, 30);
        jPanel7.add(title);
        
        JTextField txtSearch = new JTextField();
        txtSearch.setBounds(45, 50, 280, 30);
        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtSearch.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225), 2),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPanel7.add(txtSearch);
        
        JLabel searchIcon = new JLabel("🔎");
        searchIcon.setBounds(15, 50, 30, 30);
        jPanel7.add(searchIcon);
        
        JButton btnClear = new JButton("✕");
        btnClear.setBounds(335, 50, 50, 30);
        btnClear.setBackground(Color.WHITE);
        btnClear.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225), 2));
        btnClear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        jPanel7.add(btnClear);
        
        String[] cols = {"ID", "Project", "Amount", "Date", "Status"};
        modelPayments = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPayments = new JTable(modelPayments);
        tblPayments.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tblPayments.setRowHeight(28);
        tblPayments.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblPayments.setSelectionBackground(new Color(219, 234, 254));
        
        sorterPayments = new TableRowSorter<>(modelPayments);
        tblPayments.setRowSorter(sorterPayments);
        
        JScrollPane sp = new JScrollPane(tblPayments);
        sp.setBounds(15, 90, 445, 220);
        sp.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
        jPanel7.add(sp);
        
        JButton btnRefresh = createBtn("🔄 Refresh", 15, 320, 110, 35, new Color(59, 130, 246));
        btnRefresh.addActionListener(e -> loadMyPayments());
        jPanel7.add(btnRefresh);
        
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String text = txtSearch.getText();
                sorterPayments.setRowFilter(text.trim().isEmpty() ? null : RowFilter.regexFilter("(?i)" + text));
            }
        });
        
        btnClear.addActionListener(e -> {
            txtSearch.setText("");
            sorterPayments.setRowFilter(null);
        });
    }

private JPanel createCard(String title, String value, int x, int y, Color color) {
    JPanel card = new JPanel();
    card.setLayout(null);
    card.setBounds(x, y, 210, 130);
    card.setBackground(Color.WHITE);
    card.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 2));
    
    JPanel bar = new JPanel();
    bar.setBounds(0, 0, 5, 130);
    bar.setBackground(color);
    card.add(bar);
    
    JLabel lbl1 = new JLabel(title);
    lbl1.setFont(new Font("Segoe UI", Font.BOLD, 13));
    lbl1.setForeground(new Color(100, 116, 139));
    lbl1.setBounds(15, 15, 190, 20);
    card.add(lbl1);
    
    JLabel lbl2 = new JLabel(value);
    lbl2.setFont(new Font("Segoe UI", Font.BOLD, 28));
    lbl2.setBounds(15, 60, 190, 40);
    card.add(lbl2);
    
    if (title.contains("Total")) lblTotalProjects = lbl2;
    else if (title.contains("Active")) lblActiveProjects = lbl2;
    else if (title.contains("Earnings")) lblTotalEarnings = lbl2;
    else if (title.contains("Pending")) lblPendingPayments = lbl2;
    
    return card;
}
private JButton createBtn(String text, int x, int y, int w, int h, Color bg) {
    JButton btn = new JButton(text);
    btn.setBounds(x, y, w, h);
    btn.setBackground(bg);
    btn.setForeground(Color.WHITE);
    btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
    btn.setBorderPainted(false);
    btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btn.setFocusPainted(false);
    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btn.setBackground(bg.darker());
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btn.setBackground(bg);
        }
    });
    return btn;
}
   

    private void acceptProject() {
        int row = tblAvailableProjects.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a project first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int id = (int) modelAvailableProjects.getValueAt(row, 0);
        String name = (String) modelAvailableProjects.getValueAt(row, 1);
        
        int conf = JOptionPane.showConfirmDialog(this, "Accept: " + name + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            try {
                config cfg = new config();
                Connection conn = cfg.connectDB();
                String sql = "UPDATE projects SET contractor_id = ?, status = 'In Progress' WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, contractorId);
                pstmt.setInt(2, id);
                pstmt.executeUpdate();
                pstmt.close();
                conn.close();
                
                JOptionPane.showMessageDialog(this, "Project accepted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadAvailableProjects();
                loadMyProjects();
                loadDashboardStats();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void markComplete() {
          int row = tblMyProjects.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a project first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int id = (int) modelMyProjects.getValueAt(row, 0);
        String name = (String) modelMyProjects.getValueAt(row, 1);
        
        int conf = JOptionPane.showConfirmDialog(this, "Mark '" + name + "' as Completed?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            try {
                config cfg = new config();
                Connection conn = cfg.connectDB();
                String sql = "UPDATE projects SET status = 'Completed' WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
                pstmt.close();
                conn.close();
                
                JOptionPane.showMessageDialog(this, "Project completed!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadMyProjects();
                loadDashboardStats();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private String getProfilePic() {
        try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "SELECT profile_pic FROM users WHERE username = ?");
        pstmt.setString(1, loggedInUsername);
        ResultSet rs = pstmt.executeQuery();
        String pic = rs.next() ? 
            (rs.getString("profile_pic") != null ? rs.getString("profile_pic") : "") : "";
        rs.close(); pstmt.close(); conn.close();
        return pic;
    } catch (Exception e) { return ""; }
}


    private void addDefaultAvatar(JPanel avatar) {
         JLabel avatarLbl = new JLabel("👤", SwingConstants.CENTER);
    avatarLbl.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 40));
    avatarLbl.setForeground(Color.WHITE);
    avatar.add(avatarLbl);
}

    private void saveProfilePic(String absolutePath) {
        try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "UPDATE users SET profile_pic = ? WHERE username = ?");
        pstmt.setString(1, absolutePath);  // ✅ use absolutePath
        pstmt.setString(2, loggedInUsername);
        pstmt.executeUpdate();
        pstmt.close();
        conn.close();
        System.out.println("✅ Profile pic saved: " + absolutePath);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private String getEmail() {
         try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "SELECT email FROM users WHERE username = ?");
        pstmt.setString(1, loggedInUsername);
        ResultSet rs = pstmt.executeQuery();
        String email = rs.next() ? 
            (rs.getString("email") != null ? rs.getString("email") : "Not set") : "Not set";
        rs.close(); pstmt.close(); conn.close();
        return email;
    } catch (Exception e) { return "Not set"; }
}

    private Object getBio() {
      
    try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "SELECT bio FROM users WHERE username = ?");
        pstmt.setString(1, loggedInUsername);
        ResultSet rs = pstmt.executeQuery();
        
        String bio = "";
        if (rs.next()) {
            String val = rs.getString("bio");
            bio = (val != null) ? val : "";
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        return bio;
        
    } catch (Exception e) {
        e.printStackTrace();
        return "";
    }
}

    private void saveBio(String bioText) {  // ✅ renamed to bioText
    try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "UPDATE users SET bio = ? WHERE username = ?");
        pstmt.setString(1, bioText);  // ✅ use bioText
        pstmt.setString(2, loggedInUsername);
        pstmt.executeUpdate();
        pstmt.close();
        conn.close();
        System.out.println("✅ Bio saved: " + bioText);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private boolean verifyCurrentPassword(String password) {
    try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "SELECT id FROM users WHERE username = ? AND password = ?");
        pstmt.setString(1, loggedInUsername);
        pstmt.setString(2, password);
        ResultSet rs = pstmt.executeQuery();
        boolean valid = rs.next();
        rs.close(); pstmt.close(); conn.close();
        return valid;
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    }
}

private boolean changePassword(String newPassword) {
    try {
        config cfg = new config();
        Connection conn = cfg.connectDB();
        PreparedStatement pstmt = conn.prepareStatement(
            "UPDATE users SET password = ? WHERE username = ?");
        pstmt.setString(1, newPassword);
        pstmt.setString(2, loggedInUsername);
        int rows = pstmt.executeUpdate();
        pstmt.close(); conn.close();
        return rows > 0;
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    }
}
}
