/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Register.Sign_Up;
import javax.swing.JOptionPane;
import config.config;
import java.sql.*;


/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {
  
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        bback = new javax.swing.JButton();
        blog_in = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOG IN APPLICATION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });
        jPanel1.add(jtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, -1));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));

        bback.setBackground(new java.awt.Color(204, 204, 255));
        bback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bback.setText("BACK");
        bback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });
        jPanel1.add(bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        blog_in.setBackground(new java.awt.Color(204, 204, 255));
        blog_in.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        blog_in.setText("LOG IN");
        blog_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blog_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blog_inActionPerformed(evt);
            }
        });
        jPanel1.add(blog_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 250, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\f40f2281-d1ea-424c-8099-0d90ca659282.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        setSize(new java.awt.Dimension(750, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
        jpassword.requestFocus();
    }//GEN-LAST:event_jtuserActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
         new Sign_Up().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bbackActionPerformed

    private void blog_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blog_inActionPerformed
             String username = jtuser.getText().trim();
        String password = new String(jpassword.getPassword()).trim();
        
        if(username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Username and Password!", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        config cfg = new config();
        String role = cfg.validateLogin(username, password);
        
        if(role != null) {
            if(role.equals("PENDING")) {
                JOptionPane.showMessageDialog(this,
                    "⏳ Your account is pending approval.\n\n" +
                    "Please wait for admin to approve your request.\n" +
                    "You will be able to login once approved.",
                    "Pending Approval",
                    JOptionPane.WARNING_MESSAGE);
                
                jpassword.setText("");
                jtuser.requestFocus();
                return;
            }
            
            if(role.equals("NOROLE")) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Login Successful!\n\n" +
                    "Please select your role to continue.", 
                    "Welcome", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                new Dashboard.RoleSelectionDashboard(username).setVisible(true);
                return;
            }
            
            JOptionPane.showMessageDialog(this, 
                "✅ Login Successful!\n" +
                "Welcome back, " + username + "!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
            switch (role.toLowerCase()) {
                case "admin":
                    new Dashboard.AdminDashboard(username).setVisible(true);
                    break;
                case "contractor":
                    new Dashboard.ContractorDashboard(username).setVisible(true);
                    break;
                case "client":
                    new Dashboard.ClientDashboard(username).setVisible(true);
                    break;
                default:
                    new Dashboard.RoleSelectionDashboard(username).setVisible(true);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "❌ Wrong Username or Password!\n\n" +
                "Please try again.", 
                "Login Failed", 
                JOptionPane.ERROR_MESSAGE);
            
            jpassword.setText("");
            jtuser.requestFocus();
        }
    }//GEN-LAST:event_blog_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bback;
    private javax.swing.JButton blog_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables

    private boolean validateLogin(String username, String password) {
         try {
        Connection conn = new Sign_Up().connectDB();
        String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, username);
        pstmt.setString(2, password);
        
        ResultSet rs = pstmt.executeQuery();
        boolean valid = rs.next();
        
        rs.close();
        pstmt.close();
        conn.close();
        
        return valid;
        
    } catch(SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Database error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return false;
    }
    }

    

       @Override
public void setVisible(boolean b) {
    super.setVisible(b);
}
    }
