/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register;
import Login.Login;
import javax.swing.JOptionPane;
import config.config;
import java.awt.Color;
import java.sql.*;

public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Signin
     */
    public Sign_Up() {
        initComponents(); 
         setupEmailField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        bexit = new javax.swing.JButton();
        bsign_in = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREATE ACCOUNT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });
        jPanel1.add(jtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 120, -1));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        bexit.setBackground(new java.awt.Color(204, 204, 255));
        bexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bexit.setText("EXIT");
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel1.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        bsign_in.setBackground(new java.awt.Color(204, 204, 255));
        bsign_in.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsign_in.setText("SIGN IN");
        bsign_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsign_inActionPerformed(evt);
            }
        });
        jPanel1.add(bsign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 30));

        jButton1.setBackground(new java.awt.Color(2, 2, 2));
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Already have an account? Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("EMAIL");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 250, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\f40f2281-d1ea-424c-8099-0d90ca659282.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 740, 440));

        setSize(new java.awt.Dimension(753, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
        jpassword.requestFocus();
        }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        jpassword.requestFocus();  // ✅ FOCUS TO PASSWORD
    }

        // Method para check kung ang username already exists
          private boolean usernameExists(String username) {
        try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            String sql = "SELECT * FROM users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            
            ResultSet rs = pstmt.executeQuery();
            boolean exists = rs.next();
            
            rs.close();
            pstmt.close();
            conn.close();
            
            return exists;
            
        } catch(SQLException e) {
            e.printStackTrace();
            return false;
        }
    
    
            // Method para i-save ang user sa database

    }//GEN-LAST:event_jtuserActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    private void bsign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsign_inActionPerformed
       String username = jtuser.getText().trim();
        String email = jTextField1.getText().trim();  // ✅ GET FROM TEXTFIELD, NOT LABEL!
        String password = new String(jpassword.getPassword()).trim();
        
        // ✅ REMOVE PLACEHOLDER
        if (email.equals("user@example.com")) {
            email = "";
        }
        
        // ✅ VALIDATION
        if(username.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "⚠️ All fields are required!\n\n" +
                "Please fill in:\n" +
                "  • Username\n" +
                "  • Email (example: user@gmail.com)\n" +
                "  • Password",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // ✅ VALIDATE EMAIL
        if(!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this,
                "❌ Invalid Email Format!\n\n" +
                "You entered: '" + email + "'\n\n" +
                "Valid email examples:\n" +
                "  ✓ user@gmail.com\n" +
                "  ✓ john.doe@example.com\n" +
                "  ✓ contact@company.co.uk\n\n" +
                "Email must contain '@' and a domain name\n" +
                "(like gmail.com or yahoo.com)",
                "Invalid Email",
                JOptionPane.ERROR_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                jTextField1.requestFocus();  // ✅ FOCUS TEXTFIELD
                jTextField1.selectAll();
            });
            return;
        }
        
        // ✅ CHECK USERNAME
        if(usernameExists(username)) {
            JOptionPane.showMessageDialog(this,
                "❌ Username already taken!\n\n" +
                "The username '" + username + "' is already registered.\n" +
                "Please choose a different username.",
                "Registration Error",
                JOptionPane.ERROR_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                jtuser.requestFocus();
                jtuser.selectAll();
            });
            return;
        }
        
        // ✅ CHECK EMAIL
        if(emailExists(email)) {
            JOptionPane.showMessageDialog(this,
                "❌ Email already registered!\n\n" +
                "The email '" + email + "' is already in use.\n" +
                "Please use a different email address\n" +
                "or login with this email.",
                "Registration Error",
                JOptionPane.ERROR_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                jTextField1.requestFocus();  // ✅ FOCUS TEXTFIELD
                jTextField1.selectAll();
            });
            return;
        }
        
        // ✅ SAVE USER
        if(saveUser(username, email, password)) {
            JOptionPane.showMessageDialog(this,
                "✅ Account Successfully Created!\n\n" +
                "Username: " + username + "\n" +
                "Email: " + email + "\n\n" +
                "You can now login using your username or email.",
                "Welcome!",
                JOptionPane.INFORMATION_MESSAGE);
            
            new Login().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "❌ Error Creating Account\n\n" +
                "Something went wrong. Please try again.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bsign_inActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       new Login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton bsign_in;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables

    private boolean saveUser(String username, String email, String password) {
        try {
            config conf = new config();
            Connection conn = conf.connectDB();
            
            String sql = "INSERT INTO users (username, email, password, role, status) VALUES (?, ?, ?, NULL, 'active')";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, email);
            pstmt.setString(3, password);
            
            int rowsInserted = pstmt.executeUpdate();
            
            pstmt.close();
            conn.close();
            
            return rowsInserted > 0;
            
        } catch(Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public Connection connectDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void addRecord(String sql, String username, String password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String validateLogin(String username, String password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean emailExists(String email) {
       try {
            config cfg = new config();
            Connection conn = cfg.connectDB();
            String sql = "SELECT * FROM users WHERE email = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, email);
            
            ResultSet rs = pstmt.executeQuery();
            boolean exists = rs.next();
            
            rs.close();
            pstmt.close();
            conn.close();
            
            return exists;
            
        } catch(SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

   private boolean isValidEmail(String email) {
      if (email == null || email.trim().isEmpty()) {
        return false;
    }
    
    email = email.trim().toLowerCase();  // ✅ Convert to lowercase
    
    // ✅ MUST END WITH @gmail.com
    if (!email.endsWith("@gmail.com")) {
        return false;
    }
    
    // ✅ MUST HAVE SOMETHING BEFORE @gmail.com
    String username = email.replace("@gmail.com", "");
    if (username.isEmpty()) {
        return false;
    }
    
    // ✅ CHECK IF VALID FORMAT (user@gmail.com)
    int atCount = email.length() - email.replace("@", "").length();
    if (atCount != 1) {
        return false;
    }
    
    // ✅ NO SPACES ALLOWED
    if (email.contains(" ")) {
        return false;
    }
    
    return true;
    }
     
   
    private void setupEmailField() {
        jTextField1.setText("");
        jTextField1.setForeground(new Color(150, 150, 150));
        jTextField1.setToolTipText("Enter your email (e.g., user@gmail.com)");
        
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().equals("")) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }
            
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().trim().isEmpty()) {
                    jTextField1.setText("");
                    jTextField1.setForeground(new Color(150, 150, 150));
                }
            }
        });
    }
}